version: '3.8'

x-${PROJECT}-shared-conf: &shared-conf
  environment:
    - TZ=${TIME_ZONE}
  env_file:
      - env/compile.env
      - env/database.env
      - env/extractor.env
  volumes:
    - "./sources:/app/sources:rw"
    - "./server:/app/skyfire-server:rw"
    - "${WOW_PATH}:/app/wow:rw"
  tty: True
  restart: on-failure

services:
  authserver:
    image: ${PROJECT}-authserver:${UBUNTU_TAG}
    container_name: ${PROJECT}-authserver
    build: {context: ., dockerfile: container/authserver/Dockerfile}
    <<: *shared-conf
    ports:
      - "3724:3724"

  compile:
    image: ${PROJECT}-compile:${UBUNTU_TAG}
    container_name: ${PROJECT}-compile
    build: {context: ., dockerfile: container/compile/Dockerfile}
    <<: *shared-conf
    restart: no
    profiles:
      - compile

  database:
    image: ${PROJECT}-db:${DB_TAG}
    container_name: ${PROJECT}-db
    build: {context: ., dockerfile: container/database/Dockerfile}
    <<: *shared-conf
    hostname: ${PROJECT}db
    command: --max_allowed_packet=32505856
    ports:
      - "3333:3306"

  mysql:
    image: ${PROJECT}-db2:${DB2_TAG}
    container_name: ${PROJECT}-db2
    build: {context: ., dockerfile: container/database2/Dockerfile}
    <<: *shared-conf
    hostname: ${PROJECT}db2
    command: --max_allowed_packet=32505856
    ports:
      - "3336:3306"

  extractor:
    image: ${PROJECT}-extractor:${UBUNTU_TAG}
    container_name: ${PROJECT}-extractor
    build: {context: ., dockerfile: container/extractor/Dockerfile}
    <<: *shared-conf
    profiles:
      - extractor

  worldserver:
    image: ${PROJECT}-worldserver:${UBUNTU_TAG}
    container_name: ${PROJECT}-worldserver
    build: {context: ., dockerfile: container/worldserver/Dockerfile}
    <<: *shared-conf
    ports:
      - "8085:8085"
      - "3443:3443"

networks:
  default:
    name: ${PROJECT}-network
